# Welcome to Jekyll!

# Website settings
title: "Utsav Shah"
description: "In Love with Intelligence"
keywords: "Utsav,Shah,DeepLearning,MAV,MachineLearning,Robotics,IIIT"
baseurl: "/"
url: "http://diav79.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Utsav'
  first_name: 'Utsav'
  last_name: 'Shah'
  email: 'utsavdshah@gmail.com'
  facebook_username: ''
  github_username: 'diav79'
  head_img: 'static/img/landing/UtsavShah.jpg'
  desc: 'Currently a student (and also forever). Learning new things. Expanding horizons... Area of Interest: Artificial General Intelligence, Variational Calculus, Multi View Geometry. In Love with Intelligence!'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.lnk'
    name: 'Contact'
    tpl: 'links.html'
    css: 'contact'

# localization
#languages:
#  - locale: 'en'
#    flag: 'static/img/flags/United-States.png'
#  - locale: 'zh'
#    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
#donate:
#  wechat: 'static/img/pay/wechat.png'
#  alipay: 'static/img/pay/alipay.png'

# comment
#changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
#disqus:
  #name: jalpc
  #public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
#bshare:
  #uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
#ga:
  #id: UA-73784599-1

# growingIO
#gio:
  #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
